/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.quarkus.quarkus.resteasy.jsonb)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.resteasy)
    api(libs.io.quarkus.quarkus.container.image.docker)
    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.io.rest.assured.rest.assured)
}

group = "org.agoncal.quarkus.starting"
version = "1.0.0-SNAPSHOT"
description = "rest-book"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
